# Extract

In [1]:
import pandas as pd
import requests

In [2]:
url = "https://www.fema.gov/api/open/v2/DisasterDeclarationsSummaries?$top=50000"

response = requests.get(url)
data = response.json()

df = pd.DataFrame(data['DisasterDeclarationsSummaries'])

print("Jumlah data awal :", len(df))
print("Jumlah kolom :", len(df.columns))

Jumlah data awal : 50000
Jumlah kolom : 28

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   femaDeclarationString     50000 non-null  object
 1   disasterNumber            50000 non-null  int64
 2   state                     50000 non-null  object
 3   declarationType           50000 non-null  object
 4   declarationDate           50000 non-null  object
 5   fyDeclared                50000 non-null  int64
 6   incidentType              50000 non-null  object
 7   declarationTitle          50000 non-null  object
 8   ihProgramDeclared         50000 non-null  bool
 9   iaProgramDeclared         50000 non-null  bool
 10  paProgramDeclared         50000 non-null  bool
 11  hmProgramDeclared         50000 non-null  bool
 12  incidentBeginDate         50000 non-null  object
 13  incidentEndDate           49497 non-null  object
 14  disasterCloseoutDate      36172 non-null  object
 15  tribalRequest             50000 non-null  bool
 16  fipsStateCode             50000 non-null  object
 17  fipsCountyCode            50000 non-null  object
 18  placeCode                 50000 non-null  object
 19  designatedArea            50000 non-null  object
 20  declarationRequestNumber  50000 non-null  object
 21  lastIAFilingDate          17214 non-null  object
 22  incidentId                50000 non-null  object
 23  region                    50000 non-null  int64
 24  designatedIncidentTypes   6794 non-null   object
 25  lastRefresh               50000 non-null  object
 26  hash                      50000 non-null  object
 27  id                        50000 non-null  object
dtypes: bool(5), int64(3), object(20)
memory usage: 9.0+ MB

In [4]:
df.shape

(50000, 28)

# Transform

## Cek kualitas data

In [5]:
df.isnull().sum().sort_values(ascending=False)

designatedIncidentTypes     43206
lastIAFilingDate            32786
disasterCloseoutDate        13828
incidentEndDate               503
declarationDate                 0
fyDeclared                      0
incidentType                    0
declarationTitle                0
femaDeclarationString           0
disasterNumber                  0
state                           0
declarationType                 0
hmProgramDeclared               0
paProgramDeclared               0
iaProgramDeclared               0
ihProgramDeclared               0
fipsStateCode                   0
fipsCountyCode                  0
incidentBeginDate               0
tribalRequest                   0
designatedArea                  0
placeCode                       0
incidentId                      0
declarationRequestNumber        0
region                          0
lastRefresh                     0
hash                            0
id                              0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

## Handling Missing Value

In [7]:
df['designatedIncidentTypes'] = (
    df['designatedIncidentTypes']
    .fillna('Unknown')
)

In [8]:
datetime_missing = [
    "incidentEndDate",
    "disasterCloseoutDate",
    "lastIAFilingDate"
]

for col in datetime_missing:
    if col in df.columns:
        print("\nProcessing:",col)
        print(
            "Missing Before:",
            df[col].isnull().sum()
        )
        # isi missing menggunakan forward fill
        df[col] = (
            df[col]
            .fillna(method="ffill")
            .fillna(method="bfill")
        )

Processing: incidentEndDate
Missing Before: 503

Processing: disasterCloseoutDate
Missing Before: 13828

Processing: lastIAFilingDate
Missing Before: 32786

C:\Users\ASUS\AppData\Local\Temp\ipykernel_30860\4155204485.py:17: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  .fillna(method="ffill")
C:\Users\ASUS\AppData\Local\Temp\ipykernel_30860\4155204485.py:18: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  .fillna(method="bfill")

In [9]:
#kolom yang dipakai untuk analisis
df['incidentType'] = df['incidentType'].fillna('Unknown')
df['state'] = df['state'].fillna('Unknown')
df['region'] = df['region'].fillna('Unknown')
df['declarationType'] = df['declarationType'].fillna('Unknown')

In [10]:
print("Missing Value Setelah Handling")
print(df.isnull().sum().sort_values(ascending=False))

Missing Value Setelah Handling
femaDeclarationString       0
disasterNumber              0
state                       0
declarationType             0
declarationDate             0
fyDeclared                  0
incidentType                0
declarationTitle            0
ihProgramDeclared           0
iaProgramDeclared           0
paProgramDeclared           0
hmProgramDeclared           0
incidentBeginDate           0
incidentEndDate             0
disasterCloseoutDate        0
tribalRequest               0
fipsStateCode               0
fipsCountyCode              0
placeCode                   0
designatedArea              0
declarationRequestNumber    0
lastIAFilingDate            0
incidentId                  0
region                      0
designatedIncidentTypes     0
lastRefresh                 0
hash                        0
id                          0
dtype: int64

## Konversi tipe data

In [11]:
date_columns = [
    'declarationDate',
    'incidentBeginDate',
    'incidentEndDate'
]

for col in date_columns:
    df[col] = pd.to_datetime(
        df[col],
        errors='coerce'
    )

#hapus data tanpa tanggal deklarasi
df = df.dropna(
    subset=['declarationDate']
)

In [12]:
print("Tipe Data Setelah Konversi")
print(df['declarationDate'].dtype)

Tipe Data Setelah Konversi
datetime64[ns, UTC]

## Handling Duplicate

In [13]:
df = df.drop_duplicates()

## Filter periode penelitian

In [14]:
df = df[
    (df['declarationDate'].dt.year >= 2020) &
    (df['declarationDate'].dt.year <= 2024)
]

In [15]:
print("Jumlah Data Setelah Filter:")
print(df.shape)

Jumlah Data Setelah Filter:
(14296, 28)

## Time granularity

In [16]:
df['declarationDate'] = pd.to_datetime(df['declarationDate'])

df['year'] = df['declarationDate'].dt.year
df['month'] = df['declarationDate'].dt.month
df['quarter'] = df['declarationDate'].dt.quarter

In [17]:
print("Kolom Baru:")
df[['year','month','quarter']].head()

Kolom Baru:

   year  month  quarter
0  2024      8        3
1  2024      8        3
2  2024      8        3
3  2024      8        3
4  2024      8        3

## Subject Oriented

In [18]:
df = df[
    [
        'disasterNumber',
        'state',
        'region',
        'incidentType',
        'declarationType',
        'declarationDate',
        'iaProgramDeclared',
        'paProgramDeclared',
        'hmProgramDeclared',
        'year',
        'month',
        'quarter'
    ]
]

In [19]:
print("Kolom Setelah Seleksi:")
df.columns.tolist()

Kolom Setelah Seleksi:

['disasterNumber',
 'state',
 'region',
 'incidentType',
 'declarationType',
 'declarationDate',
 'iaProgramDeclared',
 'paProgramDeclared',
 'hmProgramDeclared',
 'year',
 'month',
 'quarter']

## Integration

In [20]:
df['IA'] = df['iaProgramDeclared'].astype(int)
df['PA'] = df['paProgramDeclared'].astype(int)
df['HM'] = df['hmProgramDeclared'].astype(int)

#hapus kolom lama
df = df.drop(
    columns=[
        'iaProgramDeclared',
        'paProgramDeclared',
        'hmProgramDeclared'
    ]
)

In [21]:
print("Preview Hasil Integration:")
df.head()

Preview Hasil Integration:

,disasterNumber,state,region,incidentType,declarationType,declarationDate,year,month,quarter,IA,PA,HM
0,3610,PR,2,Severe Storm,EM,2024-08-13 00:00:00+00:00,2024,8,3,0,1,0
1,5529,OR,10,Fire,FM,2024-08-09 00:00:00+00:00,2024,8,3,0,1,1
2,5528,OR,10,Fire,FM,2024-08-06 00:00:00+00:00,2024,8,3,0,1,1
3,5527,OR,10,Fire,FM,2024-08-02 00:00:00+00:00,2024,8,3,0,1,1
4,3610,PR,2,Severe Storm,EM,2024-08-13 00:00:00+00:00,2024,8,3,0,1,0

In [22]:
pip install sqlalchemy psycopg2-binary pandas

Requirement already satisfied: sqlalchemy in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (2.0.49)
Requirement already satisfied: psycopg2-binary in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (2.9.12)
Requirement already satisfied: pandas in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (2.2.3)
Requirement already satisfied: greenlet>=1 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# Load

In [9]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://postgres:inifia@127.0.0.1:5432/UAS"
)

with engine.connect() as conn:
    print("Berhasil")

Berhasil

In [24]:
df.to_sql(
    'stg_disaster',
    engine,
    if_exists='replace',
    index=False
)

print("Data berhasil dimasukkan ke PostgreSQL")

Data berhasil dimasukkan ke PostgreSQL

# ATOTI

In [25]:
import pandas as pd

df = pd.read_sql(
    "SELECT * FROM vw_disaster_analysis",
    engine
)

print(df.head())

   disasterNumber  disaster_count  year  month  quarter state  region  \
0            3610               1  2024      8        3    PR       2
1            5529               1  2024      8        3    OR      10
2            5528               1  2024      8        3    OR      10
3            5527               1  2024      8        3    OR      10
4            3610               1  2024      8        3    PR       2

   incidentType  IA  PA  HM declarationType
0  Severe Storm   0   1   0              EM
1          Fire   0   1   1              FM
2          Fire   0   1   1              FM
3          Fire   0   1   1              FM
4  Severe Storm   0   1   0              EM

In [26]:
pip install atoti sqlalchemy psycopg2-binary

Requirement already satisfied: atoti in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (0.9.14)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: sqlalchemy in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (2.0.49)
Requirement already satisfied: psycopg2-binary in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (2.9.12)
Requirement already satisfied: atoti-client==0.9.14 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from atoti) (0.9.14)
Requirement already satisfied: atoti-client-parquet==0.9.14 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from atoti) (0.9.14)
Requirement already satisfied: atoti-server==0.9.14 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from atoti) (0.9.14)
Requirement already satisfied: atoti-server-parquet==0.9.14 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from atoti) (0.9.14)
Requirement already satisfied: jdk4py<22,>=21.0.8.2 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from atoti) (21.0.8.2)
Requirement already satisfied: atoti-core==0.9.14 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from atoti-client==0.9.14->atoti) (0.9.14)
Requirement already satisfied: graphql-core>=3.2.6 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from atoti-client==0.9.14->atoti) (3.2.8)
Requirement already satisfied: httpx<1.0.dev1,>=0.28.1 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from atoti-client==0.9.14->atoti) (0.28.1)
Requirement already satisfied: numpy>=2.2.6 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from atoti-client==0.9.14->atoti) (2.4.4)
Requirement already satisfied: opentelemetry-api>=1.39.1 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from atoti-client==0.9.14->atoti) (1.41.0)
Requirement already satisfied: pandas<3.0.0rc0,>=2.2.3 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from atoti-client==0.9.14->atoti) (2.2.3)
Requirement already satisfied: py4j>=0.10.9.7 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from atoti-client==0.9.14->atoti) (0.10.9.9)
Requirement already satisfied: pyarrow>=21.0.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from atoti-client==0.9.14->atoti) (23.0.0)
Requirement already satisfied: pydantic>=2.12.3 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from atoti-client==0.9.14->atoti) (2.12.5)
Requirement already satisfied: typing-extensions>=4.15.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from atoti-client==0.9.14->atoti) (4.15.0)
Requirement already satisfied: greenlet>=1 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: anyio in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from httpx<1.0.dev1,>=0.28.1->atoti-client==0.9.14->atoti) (4.6.2.post1)
Requirement already satisfied: certifi in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from httpx<1.0.dev1,>=0.28.1->atoti-client==0.9.14->atoti) (2021.5.30)
Requirement already satisfied: httpcore==1.* in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from httpx<1.0.dev1,>=0.28.1->atoti-client==0.9.14->atoti) (1.0.7)
Requirement already satisfied: idna in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from httpx<1.0.dev1,>=0.28.1->atoti-client==0.9.14->atoti) (2.10)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from httpcore==1.*->httpx<1.0.dev1,>=0.28.1->atoti-client==0.9.14->atoti) (0.14.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from opentelemetry-api>=1.39.1->atoti-client==0.9.14->atoti) (8.7.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python312\site-packages (from pandas<3.0.0rc0,>=2.2.3->atoti-client==0.9.14->atoti) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from pandas<3.0.0rc0,>=2.2.3->atoti-client==0.9.14->atoti) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from pandas<3.0.0rc0,>=2.2.3->atoti-client==0.9.14->atoti) (2024.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from pydantic>=2.12.3->atoti-client==0.9.14->atoti) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from pydantic>=2.12.3->atoti-client==0.9.14->atoti) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from pydantic>=2.12.3->atoti-client==0.9.14->atoti) (0.4.2)
Requirement already satisfied: zipp>=3.20 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.39.1->atoti-client==0.9.14->atoti) (3.23.1)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas<3.0.0rc0,>=2.2.3->atoti-client==0.9.14->atoti) (1.16.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\asus\appdata\local\programs\python\python312\lib\site-packages (from anyio->httpx<1.0.dev1,>=0.28.1->atoti-client==0.9.14->atoti) (1.3.1)

[notice] A new release of pip is available: 24.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14296 entries, 0 to 14295
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   disasterNumber   14296 non-null  int64
 1   disaster_count   14296 non-null  int64
 2   year             14296 non-null  int64
 3   month            14296 non-null  int64
 4   quarter          14296 non-null  int64
 5   state            14296 non-null  object
 6   region           14296 non-null  int64
 7   incidentType     14296 non-null  object
 8   IA               14296 non-null  int64
 9   PA               14296 non-null  int64
 10  HM               14296 non-null  int64
 11  declarationType  14296 non-null  object
dtypes: int64(9), object(3)
memory usage: 1.3+ MB

In [28]:
import pandas as pd
import atoti as tt

df_atoti = pd.read_sql(
    "SELECT * FROM vw_disaster_analysis",
    engine
)

df_atoti["tahun"] = df_atoti["year"].astype(str)
df_atoti["month"] = df_atoti["month"].astype(str)
df_atoti["quarter"] = df_atoti["quarter"].astype(str)
df_atoti["region"] = df_atoti["region"].astype(str)

df_atoti["IA"] = df_atoti["IA"].astype(str)
df_atoti["PA"] = df_atoti["PA"].astype(str)
df_atoti["HM"] = df_atoti["HM"].astype(str)


df_atoti["IA"] = df_atoti["IA"].replace({"0": "Tidak", "1": "Ya"})
df_atoti["PA"] = df_atoti["PA"].replace({"0": "Tidak", "1": "Ya"})
df_atoti["HM"] = df_atoti["HM"].replace({"0": "Tidak", "1": "Ya"})

print(df_atoti.dtypes)
print(df_atoti.head())

Welcome to Atoti 0.9.14!

By using this community edition, you agree with the license available at https://docs.activeviam.com/products/atoti/python-sdk/latest/eula.html.
Browse the official documentation at https://docs.activeviam.com/products/atoti/python-sdk.
Join the community at https://www.atoti.io/register.

Atoti collects telemetry data, which is used to help understand how to improve the product.
If you don't wish to send usage data, you can request a trial license at https://www.atoti.io/evaluation-license-request.

You can hide this message by setting the `ATOTI_HIDE_EULA_MESSAGE` environment variable to True.
disasterNumber      int64
disaster_count      int64
year                int64
month              object
quarter            object
state              object
region             object
incidentType       object
IA                 object
PA                 object
HM                 object
declarationType    object
tahun              object
dtype: object
   disasterNumber  disaster_count  year month quarter state region  \
0            3610               1  2024     8       3    PR      2
1            5529               1  2024     8       3    OR     10
2            5528               1  2024     8       3    OR     10
3            5527               1  2024     8       3    OR     10
4            3610               1  2024     8       3    PR      2

   incidentType     IA  PA     HM declarationType tahun
0  Severe Storm  Tidak  Ya  Tidak              EM  2024
1          Fire  Tidak  Ya     Ya              FM  2024
2          Fire  Tidak  Ya     Ya              FM  2024
3          Fire  Tidak  Ya     Ya              FM  2024
4  Severe Storm  Tidak  Ya  Tidak              EM  2024

In [29]:
session = tt.Session.start()

store = session.read_pandas(
    df_atoti,
    table_name="disaster_analysis_v2",
    keys=["disasterNumber"]
)

cube = session.create_cube(store)

m = cube.measures

m["Total Disaster"] = tt.agg.sum(
    store["disaster_count"]
)

print("Atoti dashboard berhasil dibuat")
print(session.link)

Atoti dashboard berhasil dibuat
http://localhost:62813

In [30]:
# try:
#     session.close()
# except:
#     pass

# Neon Cloud

In [6]:
from sqlalchemy import create_engine

engine_neon = create_engine(
    "postgresql://neondb_owner:npg_2d7CMOQfBTSE@ep-rapid-dream-ao3gpwxy-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
)

print("Koneksi berhasil")

Koneksi berhasil

In [7]:
import pandas as pd

pd.read_sql("SELECT 1", engine_neon)

   ?column?
0         1

In [12]:
tables_to_copy = [
    "stg_disaster",
    "fact_disaster",
    "dim_time",
    "dim_state",
    "dim_incident",
    "dim_program",
    "dim_declaration"
]

for table in tables_to_copy:
    
    df_temp = pd.read_sql(
        f"SELECT * FROM {table}",
        engine
    )

    df_temp.to_sql(
        table,
        engine_neon,
        if_exists="replace",
        index=False
    )

    print(f"{table} berhasil dipindahkan")

stg_disaster berhasil dipindahkan
fact_disaster berhasil dipindahkan
dim_time berhasil dipindahkan
dim_state berhasil dipindahkan
dim_incident berhasil dipindahkan
dim_program berhasil dipindahkan
dim_declaration berhasil dipindahkan

In [10]:
df_view = pd.read_sql(
    "SELECT * FROM vw_disaster_analysis",
    engine
)

df_view.to_sql(
    "vw_disaster_analysis",
    engine_neon,
    if_exists="replace",
    index=False
)

296

In [11]:
print(df_view.shape)

(14296, 12)